name: Cron Analyze Dispatcher

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Vercel cron endpoint
        run: |
          curl -fsS "$CRON_TARGET_URL" || exit 1
        env:
          CRON_TARGET_URL: ${{ secrets.CRON_TARGET_URL }}


